### ISSUE TITLE
q_backup_and_purge_old_configuration missing

### ISSUE THREAD

**Issue by malnick** [oscar-stack/vagrant-pe_build#64]
This is a new problem I've had, running inside Vagrant 1.5.3. I've purged all my old boxes and am downloading a fresh box:

config.vm.box = "centos-64-x64-nocm"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-fusion503-nocm.box"

For some reason it thinks Puppet was installed and not purged. I can't say for sure whether this is an issue on my end, but I have confirmed that it is in fact erroring on this after a fresh download of the box above.

**Comment by ccaum** [comment]
Just ran into this issue.  The best way to handle this is to have a shell provisioner that runs after pe_builder and creates a symlink from /etc/puppetlabs/puppet/modules/module to /vagrant/module/path

**Comment by Sharpie** [comment]
As noted in this thread, this issue occurs when the PE installer thinks it is doing a clean install, but finds what appears to be pre-existing configuration. For example, a directory structure under `/etc/puppetlabs`.

In some versions of PE, there is an undocumented answer, `q_skip_backup=y` that can be used to disable this check. Starting with version pe_build version 0.11.0, this can easily be added to an answer file when needed by using the `answer_extras` configuration option:

```ruby
node.vm.provision :pe_bootstrap do |p|
  p.role = :master
  p.version = '3.8.2'
  p.download_root = 'http://pe-releases.puppetlabs.lan/:version'
  p.answer_extras = [
    'q_skip_backup=y',
  ]
end

# This would cause an installation error without q_skip_backup
node.vm.synced_folder File.join(PROJECT_ROOT, 'provisioning/environments'),
  '/etc/puppetlabs/puppet/environments'
```

Starting with 2015.2.0, the PE installer is less picky about pre-existing configuration and `q_skip_backup` is no longer necessary.

**Comment by Sharpie** [comment]
I'm going to close this as "won't fix" because this error arises when PE 3.x is installed in an unclean environment. Working around this in the `pe_build` answer file templates would cover up two very important issues:

  - The base VM images in use are dirty, and whichever process is building them (i.e. Packer) needs a better cleanup step that removes all remnants of a PE installation.

  - You are intentionally pre-seeding PE data (such as modules or Hiera data). In this case, you also need to intentionally customize your answer files. Otherwise you'll have an installation that works in development due to `pe_build` "magic", but fails in production because you didn't know that the answer file needed to be customized.

This issue is also mitigated by: 

  - 0.12.0 of `vagrant-pe_build` makes it easier to append customizations, such as `q_skip_backup=y`,  to the answer file via `answer_extras`.

  - Starting with version 2015.2.0, PE is more lenient about what can exist in `/etc/puppetlabs` prior to installation. Specifically, pre-seeding Hiera data is now a use case covered by acceptance tests.
