### ISSUE TITLE
answers file (master.txt) not being interpreted as expected on Windows 7 

### ISSUE THREAD

**Issue by prolixalias** [oscar-stack/vagrant-pe_build#65]
$ vagrant --version
Vagrant 1.5.1
$ vagrant plugin list
vagrant-auto_network (1.0.1)
vagrant-hosts (2.1.5)
vagrant-pe_build (0.8.8)
oscar (0.4.1)
vagrant-login (1.0.1, system)
vagrant-share (1.1.0, system)

Hello. Running in "git bash" and cmd.exe on Windows 7 --- I'm seeing the following output during provisioning:

-> puppet master

   The puppet master serves configurations to a group of puppet
   agent nodes. This role also provides MCollective's message queue
   and client interface. It should be installed on a robust,
   dedicated server.

?? Install puppet master? [y/N] y
?? Install puppet master? [y/N]

Stderr from the command:

stdin: is not a tty
!! ERROR: Answer must be either "y", "n" or <ENTER> for "n"
/vagrant/.pe_build/puppet-enterprise-3.1.0-ubuntu-12.04-amd64/utilities: line 53
7: t_ask__answered: parameter null or not set

Installer doesn't seem to be receiving the "y" properly. Please let me know how to diagnose?

Many thanks.

-Paul

**Comment by Sharpie** [comment]
Closing this one since the installation routines have been re-factored several times in the past year and the PE installer is drastically different than the 2.x and 3.x days. I know of at least one person using pe_build 0.18.0 with Virtualbox and bash in the Windows Subsystem for Linux without issue.

Do open a new ticket with updated output if this failure is still occurring.
